### ISSUE TITLE
GetSigner: Error from db.Prepare: no such column: addr

### ISSUE THREAD

**Issue by romu42** [DNSSEC-Provisioning/music#24]
The following add command: 
```
❯ ../sbin/music-cli signer add --address 1.1.1.1 --auth bobisbobauth -m ddns
2021/11/09 21:36:31 RootCA loaded
2021/11/09 21:36:31 Error from GenericAPIpost: Post "https://127.0.0.1:8080/api/v1/signer": stream error: stream ID 1; INTERNAL_ERROR
Error from AddSigner: Post "https://127.0.0.1:8080/api/v1/signer": stream error: stream ID 1; INTERNAL_ERROR
```

Causes the following error:
```
GetSigner: Error from db.Prepare: no such column: addr
2021/11/09 21:36:31 http2: panic serving 127.0.0.1:60578: runtime error: invalid memory address or nil pointer dereference
goroutine 6 [running]:
net/http.(*http2serverConn).runHandler.func1()
	/usr/local/go/src/net/http/h2_bundle.go:5825 +0x125
panic({0x4624120, 0x4ab03a0})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
database/sql.(*Stmt).QueryContext(0x0, {0x475cd30, 0xc00019e008}, {0xc0002137e0, 0x1, 0x1})
	/usr/local/go/src/database/sql/sql.go:2726 +0x82
database/sql.(*Stmt).QueryRowContext(0x0, {0x475cd30, 0xc00019e008}, {0xc0002137e0, 0xc0002137f0, 0x1})
	/usr/local/go/src/database/sql/sql.go:2804 +0x2c
database/sql.(*Stmt).QueryRow(...)
	/usr/local/go/src/database/sql/sql.go:2826
github.com/DNSSEC-Provisioning/music/common.(*MusicDB).GetSigner(0xc000190510, {0x0, 0x0})
	/Users/roger.murray/Working/music/common/signerops.go:90 +0x155
main.APIsigner.func1({0x47599f8, 0xc000010010}, 0xc00017a300)
	/Users/roger.murray/Working/music/musicd/apiserver.go:272 +0x2eb
net/http.HandlerFunc.ServeHTTP(0xc00017a200, {0x47599f8, 0xc000010010}, 0x0)
	/usr/local/go/src/net/http/server.go:2046 +0x2f
github.com/gorilla/mux.(*Router).ServeHTTP(0xc00011c000, {0x47599f8, 0xc000010010}, 0xc0000d4100)
	/Users/roger.murray/go/pkg/mod/github.com/gorilla/mux@v1.8.0/mux.go:210 +0x1cf
net/http.serverHandler.ServeHTTP({0x0}, {0x47599f8, 0xc000010010}, 0xc0000d4100)
	/usr/local/go/src/net/http/server.go:2878 +0x43b
net/http.initALPNRequest.ServeHTTP({{0x475cda0, 0xc00011ad80}, 0xc000174000, {0xc000156000}}, {0x47599f8, 0xc000010010}, 0xc0000d4100)
	/usr/local/go/src/net/http/server.go:3479 +0x245
net/http.(*http2serverConn).runHandler(0x4758da0, 0x4af77f0, 0x0, 0x0)
	/usr/local/go/src/net/http/h2_bundle.go:5832 +0x78
created by net/http.(*http2serverConn).processHeaders
	/usr/local/go/src/net/http/h2_bundle.go:5562 +0x510
```

**Comment by romu42** [comment]
I had an old database laying around and the schema for signers had changed. Do we need to fix this?

**Comment by romu42** [comment]
Closing this issue.  Not relevant until we have decided 100% on database model and how we handle it.
